### ISSUE TITLE
📄 Roadmap to release v1.0.0

### ISSUE THREAD

**Issue by mnik01** [mnik01/sapar-open#18]
# Roadmap
- [ ] Post page
  - i18n full support
  - Several posts
- [ ] Main page

# After release
- [ ] E2E and unit tests coverage,
- [ ] Add formatted + linter
- [ ] Performance optimizations 
- [ ] Roadmap to release v2.0.0
